version: '3.8'

services:
  client:
    command: npm run dev
    environment:
      NODE_ENV: development
    image: node:12-alpine
    ports:
      - 8080:8080
    volumes:
      - ./services/client:/app
    working_dir: /app